# Generated by Django 2.1.2 on 2018-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=64, verbose_name='设备名字')),
                ('d_number', models.CharField(max_length=128, verbose_name='设备编号')),
                ('d_located_style', models.CharField(choices=[('0', 'absolute'), ('1', 'relative')], max_length=32, verbose_name='定位方式')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
            },
        ),
    ]
