# Generated by Django 2.1.2 on 2018-10-31 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20181031_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_gps_jd', models.CharField(max_length=64, verbose_name='经度')),
                ('a_gps_wd', models.CharField(max_length=64, verbose_name='维度')),
                ('a_update_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('r_device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '记录',
                'verbose_name_plural': '记录',
            },
        ),
    ]
