# Generated by Django 2.1.2 on 2018-11-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor',
            name='a_name',
            field=models.CharField(default='', max_length=512, verbose_name='坐标系名称'),
        ),
    ]
