# Generated by Django 2.1.2 on 2018-11-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_anchor_a_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='anchor',
            name='a_tangle',
            field=models.CharField(default='', max_length=64, verbose_name='角度'),
        ),
        migrations.AddField(
            model_name='anchor',
            name='a_x_length',
            field=models.CharField(default='', max_length=64, verbose_name='X长'),
        ),
        migrations.AddField(
            model_name='anchor',
            name='a_y_length',
            field=models.CharField(default='', max_length=64, verbose_name='Y长'),
        ),
        migrations.AddField(
            model_name='device',
            name='d_CONST_A',
            field=models.CharField(default='', max_length=64, verbose_name='特征值A'),
        ),
        migrations.AddField(
            model_name='device',
            name='d_CONST_N',
            field=models.CharField(default='', max_length=64, verbose_name='特征值N'),
        ),
    ]
