# Generated by Django 2.1.2 on 2019-05-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20190202_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowupload',
            name='device_id',
            field=models.CharField(default='', max_length=128, verbose_name='设备ID'),
        ),
    ]
