# Generated by Django 2.1.2 on 2019-05-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20190505_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowupload',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=16, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='record',
            name='r_device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Device', verbose_name='设备编号'),
        ),
        migrations.AlterField(
            model_name='rowupload',
            name='successful',
            field=models.BooleanField(default=False, verbose_name='合法'),
        ),
    ]
